backup:
  folder: "/var/www/backups/"
  fileName: "backup_name"
  backupExtension: ".sql"

dump:
  ignoreTable: "mysql.event"
  addDropTable: true

s3:
  key: "s3_key"
  secret: "s3_secret"
  region: "s3_region"
  bucket: "s3_bucket"
  endpoint: "s3_endpoint"
  backupFolder: "backups/"

telegram:
  apiToken: "api_token_from_bot_father"
  chatIds: [1, 2, 3]